name: CI

on: push

jobs:

  test-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install -r requirements.txt
      - run: jupyter execute *.ipynb

  test-conda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
      - run: jupyter execute *.ipynb

  slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install -r requirements.txt
      - run: jupyter nbconvert *.ipynb --to slides --execute --SlidesExporter.file_extension=".html" --SlidesExporter.reveal_transition="convex"
      - run: mv *.html dist/.
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/"

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: slides
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
